name = "hebao-keeper"
main = "src/index.ts"
compatibility_date = "2026-08-27"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "hebao"
database_id = "15732dfc-18e3-4696-b1b3-f883e0a32fab"

[[durable_objects.bindings]]
name = "CLAIM_RUNNER"
class_name = "ClaimRunner"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClaimRunner"]

[vars]
BASE_URL = "https://xcxp.bj.10086.cn"

[assets]
directory = "./public"
binding = "ASSETS"
